Next_Ticket_ID: 1
Assignee:
- Admin
- Mod
Phrases:
  keine_antwort: 'Du hast lange nicht mehr auf das Ticket geantwortet... deshalb wird es erstmal geschlossen!'
  erledigt: 'Erledigt!'
  done: 'Erledigt!'
  gesichert: 'Deine Region wurde gesichert. Viel Spaß beim Bauen!'
  hinzugefuegt: 'Dein Mitspieler wurde zu der Region hinzugefuegt!'
  setwarp: 'Benutze bitte /ticket setwarp <#> dort, wo du Hilfe benötigst!'
  danke: 'Vielen Dank!'
  log_benutzen: 'Benutze bitte /ticket log <#> <Nachricht> um auf das Ticket zu antworten!'
  gratulation: 'Herzlichen Glückwunsch!'
  erweitert: 'Deine Region wurde erweitert. Viel Spaß!'